// <auto-generated />
using System;
using KeimheanCafePOS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KeimheanCafePOS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251123055502_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KeimheanCafePOS.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(5990),
                            ImageUrl = "https://images.unsplash.com/photo-1645445644664-8f44112f334c?w=400",
                            IsActive = true,
                            Name = "Espresso",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(6560),
                            ImageUrl = "https://images.unsplash.com/photo-1708430651927-20e2e1f1e8f7?w=400",
                            IsActive = true,
                            Name = "Cappuccino",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(6560),
                            ImageUrl = "https://images.unsplash.com/photo-1582152747136-af63c112fce5?w=400",
                            IsActive = true,
                            Name = "Latte",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(6560),
                            ImageUrl = "https://images.unsplash.com/photo-1669872484166-e11b9638b50e?w=400",
                            IsActive = true,
                            Name = "Americano",
                            Price = 2.80m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(6570),
                            ImageUrl = "https://images.unsplash.com/photo-1618576230663-9714aecfb99a?w=400",
                            IsActive = true,
                            Name = "Mocha",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(6570),
                            ImageUrl = "https://images.unsplash.com/photo-1683649197410-c58e48ce4d40?w=400",
                            IsActive = true,
                            Name = "Iced Latte",
                            Price = 4.20m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(6570),
                            ImageUrl = "https://images.unsplash.com/photo-1592663527359-cf6642f54cff?w=400",
                            IsActive = true,
                            Name = "Iced Mocha",
                            Price = 4.80m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(6570),
                            ImageUrl = "https://images.unsplash.com/photo-1681026859292-58c3b2041bfd?w=400",
                            IsActive = true,
                            Name = "Iced Americano",
                            Price = 3.20m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(6570),
                            ImageUrl = "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=400",
                            IsActive = true,
                            Name = "Iced Caramel Macchiato",
                            Price = 5.20m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(6570),
                            ImageUrl = "https://images.unsplash.com/photo-1561641377-f7456d23aa9b?w=400",
                            IsActive = true,
                            Name = "Cold Brew",
                            Price = 4.20m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Tea",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(6570),
                            ImageUrl = "https://images.unsplash.com/photo-1729259586570-639957809271?w=400",
                            IsActive = true,
                            Name = "Green Tea",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Tea",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(6570),
                            ImageUrl = "https://images.unsplash.com/photo-1498604636225-6b87a314baa0?w=400",
                            IsActive = true,
                            Name = "Earl Grey",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Tea",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(6570),
                            ImageUrl = "https://images.unsplash.com/photo-1578899952107-9c390f1af1b7?w=400",
                            IsActive = true,
                            Name = "Chai Latte",
                            Price = 3.80m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Tea",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(6570),
                            ImageUrl = "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=400",
                            IsActive = true,
                            Name = "Matcha Latte",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Pastry",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(6570),
                            ImageUrl = "https://images.unsplash.com/photo-1712723247648-64a03ba7c333?w=400",
                            IsActive = true,
                            Name = "Croissant",
                            Price = 3.00m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Pastry",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(6570),
                            ImageUrl = "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=400",
                            IsActive = true,
                            Name = "Blueberry Muffin",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Pastry",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(6570),
                            ImageUrl = "https://images.unsplash.com/photo-1700448293876-07dca826c161?w=400",
                            IsActive = true,
                            Name = "Chocolate Cake",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Pastry",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(6570),
                            ImageUrl = "https://images.unsplash.com/photo-1716579866950-54abe7d4286f?w=400",
                            IsActive = true,
                            Name = "Cheesecake",
                            Price = 5.50m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Snack",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(6570),
                            ImageUrl = "https://images.unsplash.com/photo-1657418830273-40c19cfff4d7?w=400",
                            IsActive = true,
                            Name = "Chocolate Chip Cookie",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Snack",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(6570),
                            ImageUrl = "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400",
                            IsActive = true,
                            Name = "Brownie",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 21,
                            Category = "Snack",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(6580),
                            ImageUrl = "https://images.unsplash.com/photo-1732393157398-daaf2efd2f6c?w=400",
                            IsActive = true,
                            Name = "Macarons",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 22,
                            Category = "Snack",
                            CreatedAt = new DateTime(2025, 11, 23, 5, 55, 2, 445, DateTimeKind.Utc).AddTicks(6580),
                            ImageUrl = "https://images.unsplash.com/photo-1597419765826-5b03fa018c18?w=400",
                            IsActive = true,
                            Name = "Donut",
                            Price = 2.80m
                        });
                });

            modelBuilder.Entity("KeimheanCafePOS.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CashReceived")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CashierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ChangeGiven")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TransactionDate");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("KeimheanCafePOS.Domain.Entities.TransactionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionItems");
                });

            modelBuilder.Entity("KeimheanCafePOS.Domain.Entities.TransactionItem", b =>
                {
                    b.HasOne("KeimheanCafePOS.Domain.Entities.Transaction", "Transaction")
                        .WithMany("Items")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("KeimheanCafePOS.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
