// <auto-generated />
using System;
using KeimheanCafePOS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KeimheanCafePOS.Infrastructure.src.KeimheanCafePOS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251127032502_UpdateProductImagePaths")]
    partial class UpdateProductImagePaths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KeimheanCafePOS.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1579992357154-faf4bde95b3d?w=500&q=80",
                            IsActive = true,
                            Name = "Espresso",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1534778101976-62847782c213?w=500&q=80",
                            IsActive = true,
                            Name = "Cappuccino",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1561047029-3000c68339ca?w=500&q=80",
                            IsActive = true,
                            Name = "Latte",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&q=80",
                            IsActive = true,
                            Name = "Americano",
                            Price = 2.80m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1607260550778-aa9d29444ce1?w=500&q=80",
                            IsActive = true,
                            Name = "Mocha",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=500&q=80",
                            IsActive = true,
                            Name = "Iced Latte",
                            Price = 4.20m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1642647391072-6a2416f048e5?w=500&q=80",
                            IsActive = true,
                            Name = "Iced Mocha",
                            Price = 4.80m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1662047102608-a6f2e492411f?w=500&q=80",
                            IsActive = true,
                            Name = "Iced Americano",
                            Price = 3.20m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1599305090598-fe179d501227?w=500&q=80",
                            IsActive = true,
                            Name = "Iced Caramel Macchiato",
                            Price = 5.20m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=500&q=80",
                            IsActive = true,
                            Name = "Cold Brew",
                            Price = 4.20m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Tea",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1627435601361-ec25f5b1d0e5?w=500&q=80",
                            IsActive = true,
                            Name = "Green Tea",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Tea",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=500&q=80",
                            IsActive = true,
                            Name = "Earl Grey",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Tea",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&q=80",
                            IsActive = true,
                            Name = "Chai Latte",
                            Price = 3.80m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Tea",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=500&q=80",
                            IsActive = true,
                            Name = "Matcha Latte",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Pastry",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=500&q=80",
                            IsActive = true,
                            Name = "Croissant",
                            Price = 3.00m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Pastry",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1607478900766-efe13248b125?w=500&q=80",
                            IsActive = true,
                            Name = "Blueberry Muffin",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Pastry",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&q=80",
                            IsActive = true,
                            Name = "Chocolate Cake",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Pastry",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1533134486753-c833f0ed4866?w=500&q=80",
                            IsActive = true,
                            Name = "Cheesecake",
                            Price = 5.50m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Snack",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=500&q=80",
                            IsActive = true,
                            Name = "Chocolate Chip Cookie",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Snack",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1607920591413-4ec007e70023?w=500&q=80",
                            IsActive = true,
                            Name = "Brownie",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 21,
                            Category = "Snack",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=500&q=80",
                            IsActive = true,
                            Name = "Macarons",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 22,
                            Category = "Snack",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=500&q=80",
                            IsActive = true,
                            Name = "Donut",
                            Price = 2.80m
                        },
                        new
                        {
                            Id = 23,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=500&q=80",
                            IsActive = true,
                            Name = "Flat White",
                            Price = 3.80m
                        },
                        new
                        {
                            Id = 24,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1511920170033-f8396924c348?w=500&q=80",
                            IsActive = true,
                            Name = "Cortado",
                            Price = 3.30m
                        },
                        new
                        {
                            Id = 25,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1557006021-b85faa2bc5e2?w=500&q=80",
                            IsActive = true,
                            Name = "Macchiato",
                            Price = 3.00m
                        },
                        new
                        {
                            Id = 26,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1578374173703-14c49d07ac86?w=500&q=80",
                            IsActive = true,
                            Name = "Affogato",
                            Price = 5.50m
                        },
                        new
                        {
                            Id = 27,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1514066558159-fc8c737ef259?w=500&q=80",
                            IsActive = true,
                            Name = "Irish Coffee",
                            Price = 6.50m
                        },
                        new
                        {
                            Id = 28,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1562095241-8c6714fd4178?w=500&q=80",
                            IsActive = true,
                            Name = "Vietnamese Coffee",
                            Price = 4.80m
                        },
                        new
                        {
                            Id = 29,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=500&q=80",
                            IsActive = true,
                            Name = "Nitro Cold Brew",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 30,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=500&q=80",
                            IsActive = true,
                            Name = "Spanish Latte",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 31,
                            Category = "Tea",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=500&q=80",
                            IsActive = true,
                            Name = "Jasmine Tea",
                            Price = 3.00m
                        },
                        new
                        {
                            Id = 32,
                            Category = "Tea",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?w=500&q=80",
                            IsActive = true,
                            Name = "Oolong Tea",
                            Price = 3.20m
                        },
                        new
                        {
                            Id = 33,
                            Category = "Tea",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=500&q=80",
                            IsActive = true,
                            Name = "White Tea",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 34,
                            Category = "Tea",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=500&q=80",
                            IsActive = true,
                            Name = "Rooibos Tea",
                            Price = 3.00m
                        },
                        new
                        {
                            Id = 35,
                            Category = "Tea",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1587080266227-677cc2a4e76e?w=500&q=80",
                            IsActive = true,
                            Name = "Chamomile Tea",
                            Price = 3.00m
                        },
                        new
                        {
                            Id = 36,
                            Category = "Tea",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500&q=80",
                            IsActive = true,
                            Name = "Peppermint Tea",
                            Price = 2.80m
                        },
                        new
                        {
                            Id = 37,
                            Category = "Tea",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500&q=80",
                            IsActive = true,
                            Name = "Khmer Iced Tea",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 38,
                            Category = "Tea",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1525385133512-2f3bdd039054?w=500&q=80",
                            IsActive = true,
                            Name = "Bubble Tea",
                            Price = 5.50m
                        },
                        new
                        {
                            Id = 39,
                            Category = "Pastry",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1623334044303-241021148842?w=500&q=80",
                            IsActive = true,
                            Name = "Pain au Chocolat",
                            Price = 3.20m
                        },
                        new
                        {
                            Id = 40,
                            Category = "Pastry",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&q=80",
                            IsActive = true,
                            Name = "Cinnamon Roll",
                            Price = 3.80m
                        },
                        new
                        {
                            Id = 41,
                            Category = "Pastry",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?w=500&q=80",
                            IsActive = true,
                            Name = "Danish Pastry",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 42,
                            Category = "Pastry",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=500&q=80",
                            IsActive = true,
                            Name = "Scone",
                            Price = 2.80m
                        },
                        new
                        {
                            Id = 43,
                            Category = "Pastry",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://www.pngall.com/wp-content/uploads/5/Chocolate-Cake-PNG-Free-Download.png",
                            IsActive = true,
                            Name = "Banana Bread",
                            Price = 3.20m
                        },
                        new
                        {
                            Id = 44,
                            Category = "Pastry",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1621303837174-89787a7d4729?w=500&q=80",
                            IsActive = true,
                            Name = "Carrot Cake",
                            Price = 5.20m
                        },
                        new
                        {
                            Id = 45,
                            Category = "Pastry",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://pngimg.com/uploads/cake/cake_PNG13097.png",
                            IsActive = true,
                            Name = "Red Velvet Cake",
                            Price = 5.80m
                        },
                        new
                        {
                            Id = 46,
                            Category = "Pastry",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500&q=80",
                            IsActive = true,
                            Name = "Tiramisu",
                            Price = 6.00m
                        },
                        new
                        {
                            Id = 47,
                            Category = "Snack",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=500&q=80",
                            IsActive = true,
                            Name = "Oatmeal Cookie",
                            Price = 2.20m
                        },
                        new
                        {
                            Id = 48,
                            Category = "Snack",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1603532648955-039310d9ed75?w=500&q=80",
                            IsActive = true,
                            Name = "Sugar Cookie",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 49,
                            Category = "Snack",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "/icons/photo/PeanutButterCookie.jpg",
                            IsActive = true,
                            Name = "Peanut Butter Cookie",
                            Price = 2.30m
                        },
                        new
                        {
                            Id = 50,
                            Category = "Snack",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "/icons/photo/Biscotti.jpg",
                            IsActive = true,
                            Name = "Biscotti",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 51,
                            Category = "Snack",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "/icons/photo/GranolaBar.jpg",
                            IsActive = true,
                            Name = "Granola Bar",
                            Price = 2.80m
                        },
                        new
                        {
                            Id = 52,
                            Category = "Snack",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1481391243133-f96216dcb5d2?w=500&q=80",
                            IsActive = true,
                            Name = "Chocolate Truffle",
                            Price = 3.80m
                        },
                        new
                        {
                            Id = 53,
                            Category = "Snack",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1558636508-e0db3814bd1d?w=500&q=80",
                            IsActive = true,
                            Name = "Pretzel",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 54,
                            Category = "Snack",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=500&q=80",
                            IsActive = true,
                            Name = "Muffin Chocolate",
                            Price = 3.50m
                        });
                });

            modelBuilder.Entity("KeimheanCafePOS.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CashReceived")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CashierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ChangeGiven")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("KeimheanCafePOS.Domain.Entities.TransactionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionItems");
                });

            modelBuilder.Entity("KeimheanCafePOS.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("FullName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastLoginAt");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Phone");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("Role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Role");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff@keimhean.cafe",
                            FullName = "Staff Member",
                            IsActive = true,
                            PasswordHash = "10176e7b7b24d317acfcf8d2064cfd2f24e154f7b5a96603077d5ef813d6a6b6",
                            Role = 0,
                            Username = "staff"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@keimhean.cafe",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9",
                            Role = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("KeimheanCafePOS.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("KeimheanCafePOS.Domain.Entities.User", null)
                        .WithMany("Transactions")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("KeimheanCafePOS.Domain.Entities.TransactionItem", b =>
                {
                    b.HasOne("KeimheanCafePOS.Domain.Entities.Transaction", "Transaction")
                        .WithMany("Items")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("KeimheanCafePOS.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("KeimheanCafePOS.Domain.Entities.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
