// <auto-generated />
using System;
using KeimheanCafePOS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KeimheanCafePOS.Infrastructure.src.KeimheanCafePOS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251125051923_FixStaffPasswordHash")]
    partial class FixStaffPasswordHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KeimheanCafePOS.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1579992357154-faf4bde95b3d?w=500&q=80",
                            IsActive = true,
                            Name = "Espresso",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1534778101976-62847782c213?w=500&q=80",
                            IsActive = true,
                            Name = "Cappuccino",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1561047029-3000c68339ca?w=500&q=80",
                            IsActive = true,
                            Name = "Latte",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&q=80",
                            IsActive = true,
                            Name = "Americano",
                            Price = 2.80m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1607260550778-aa9d29444ce1?w=500&q=80",
                            IsActive = true,
                            Name = "Mocha",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=500&q=80",
                            IsActive = true,
                            Name = "Iced Latte",
                            Price = 4.20m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1642647391072-6a2416f048e5?w=500&q=80",
                            IsActive = true,
                            Name = "Iced Mocha",
                            Price = 4.80m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1662047102608-a6f2e492411f?w=500&q=80",
                            IsActive = true,
                            Name = "Iced Americano",
                            Price = 3.20m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1599305090598-fe179d501227?w=500&q=80",
                            IsActive = true,
                            Name = "Iced Caramel Macchiato",
                            Price = 5.20m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Coffee",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=500&q=80",
                            IsActive = true,
                            Name = "Cold Brew",
                            Price = 4.20m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Tea",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1627435601361-ec25f5b1d0e5?w=500&q=80",
                            IsActive = true,
                            Name = "Green Tea",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Tea",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1597318281699-3a108c3d1381?w=500&q=80",
                            IsActive = true,
                            Name = "Earl Grey",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Tea",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&q=80",
                            IsActive = true,
                            Name = "Chai Latte",
                            Price = 3.80m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Tea",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1536013564249-9c83f0f97155?w=500&q=80",
                            IsActive = true,
                            Name = "Matcha Latte",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Pastry",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=500&q=80",
                            IsActive = true,
                            Name = "Croissant",
                            Price = 3.00m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Pastry",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1607478900766-efe13248b125?w=500&q=80",
                            IsActive = true,
                            Name = "Blueberry Muffin",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Pastry",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&q=80",
                            IsActive = true,
                            Name = "Chocolate Cake",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Pastry",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1533134486753-c833f0ed4866?w=500&q=80",
                            IsActive = true,
                            Name = "Cheesecake",
                            Price = 5.50m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Snack",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=500&q=80",
                            IsActive = true,
                            Name = "Chocolate Chip Cookie",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Snack",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1607920591413-4ec007e70023?w=500&q=80",
                            IsActive = true,
                            Name = "Brownie",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 21,
                            Category = "Snack",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=500&q=80",
                            IsActive = true,
                            Name = "Macarons",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 22,
                            Category = "Snack",
                            CreatedAt = new DateTime(2025, 11, 23, 9, 39, 43, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=500&q=80",
                            IsActive = true,
                            Name = "Donut",
                            Price = 2.80m
                        });
                });

            modelBuilder.Entity("KeimheanCafePOS.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CashReceived")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CashierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ChangeGiven")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("KeimheanCafePOS.Domain.Entities.TransactionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionItems");
                });

            modelBuilder.Entity("KeimheanCafePOS.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("FullName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastLoginAt");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Phone");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("Role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Role");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff@keimhean.cafe",
                            FullName = "Staff Member",
                            IsActive = true,
                            PasswordHash = "10176e7b7b24d317acfcf8d2064cfd2f24e154f7b5a96603077d5ef813d6a6b6",
                            Role = 0,
                            Username = "staff"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@keimhean.cafe",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9",
                            Role = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("KeimheanCafePOS.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("KeimheanCafePOS.Domain.Entities.User", null)
                        .WithMany("Transactions")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("KeimheanCafePOS.Domain.Entities.TransactionItem", b =>
                {
                    b.HasOne("KeimheanCafePOS.Domain.Entities.Transaction", "Transaction")
                        .WithMany("Items")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("KeimheanCafePOS.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("KeimheanCafePOS.Domain.Entities.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
